name: 'Ношу шлем, тяжело дышу'
markdown: kramdown
pygments: true
exclude: ['Gemfile', 'Gemfile.lock', 'makefile']
future: false
google_adsense: true
google_analytics: true
disqus: true
rss: http://feeds.feedburner.com/anton-shuvalov/FJHar
paginate: 20
paginate_path: archive/:num
# lsi: true

production_url: http://anton-shuvalov.info
# baseurl: http://anton-shuvalov.info # ???
permalink: /:year/:month/:day/:title
ga_id: UA-26825614-2

author:
  email: anton_shuvalov@me.com
  github: https://github.com/shuvalov-anton
  twitter: https://twitter.com/shuvalov_anton
  facebook: https://www.facebook.com/a8h333
  gplus: https://plus.google.com/u/0/106326627323747767129?rel=author
  soundcloud: https://soundcloud.com/asheee/tracks