name: 'Ношу шлем, тяжело дышу'
markdown: kramdown
pygments: true
exclude: ['Gemfile', 'Gemfile.lock']

# production_url : http://anton-shuvalov.info
# baseurl: http://anton-shuvalov.info # ???
permalink: /:year/:month/:day/:title

author:
  name: Антон Шувалов
  email: anton_shuvalov@me.com
  github: http://github.com/shuvalov-anton
  twitter: http://twitter.com/shuvalov_anton
  facebook: http://facebook.com/a8h333
  soundcloud: http://soundcloud.com/a8h333